--[[

@author Kurki
@copyright (c)2026 Profession Master. All Rights Reserved.

--]]

-- Zone name lookup for bcc (auto-generated by tools/build-recipe-sources.ps1)
-- Keyed by zoneId (areaID), used to resolve zone names from recipe-sources data
local zoneNames = {
    [2366] = "The Black Morass",
    [2367] = "Old Hillsbrad Foothills",
    [3358] = "Arathi Basin",
    [3430] = "Eversong Woods",
    [3433] = "Ghostlands",
    [3457] = "Karazhan",
    [3483] = "Hellfire Peninsula",
    [3487] = "Silvermoon City",
    [3518] = "Nagrand",
    [3519] = "Terokkar Forest",
    [3520] = "Shadowmoon Valley",
    [3521] = "Zangarmarsh",
    [3522] = "Blade's Edge Mountains",
    [3523] = "Netherstorm",
    [3524] = "Azuremyst Isle",
    [3525] = "Bloodmyst Isle",
    [3557] = "The Exodar",
    [3562] = "Hellfire Ramparts",
    [3606] = "Hyjal Summit",
    [3607] = "Serpentshrine Cavern",
    [3703] = "Shattrath City",
    [3713] = "The Blood Furnace",
    [3714] = "The Shattered Halls",
    [3715] = "The Steamvault",
    [3716] = "The Underbog",
    [3717] = "The Slave Pens",
    [3789] = "Shadow Labyrinth",
    [3790] = "Auchenai Crypts",
    [3791] = "Sethekk Halls",
    [3792] = "Mana-Tombs",
    [3805] = "Zul'Aman",
    [3845] = "Tempest Keep",
    [3847] = "The Botanica",
    [3848] = "The Arcatraz",
    [3849] = "The Mechanar",
    [3923] = "Gruul's Lair",
    [3959] = "Black Temple",
    [4075] = "Sunwell Plateau",
    [4080] = "Isle of Quel'Danas",
    [4131] = "Magisters' Terrace",
}

_G.professionMaster:CreateModel("zone-names-bcc", zoneNames);
