--[[

@author Kurki
@copyright (c)2026 Profession Master. All Rights Reserved.

--]]

-- Zone name lookup for cata (auto-generated by tools/build-recipe-sources.ps1)
-- Keyed by zoneId (areaID), used to resolve zone names from recipe-sources data
local zoneNames = {
    [616] = "Mount Hyjal",
    [4706] = "Ruins of Gilneas",
    [4709] = "Southern Barrens",
    [4714] = "Gilneas",
    [4720] = "Abyssal Depths",
    [4742] = "Uldum",
    [4755] = "Blackrock Caverns",
    [4815] = "The Stonecore",
    [4922] = "Twilight Highlands",
    [4926] = "Blackwing Descent",
    [4945] = "Halls of Origination",
    [4950] = "Grim Batol",
    [4987] = "The Bastion of Twilight",
    [5004] = "Throne of the Tides",
    [5034] = "Uldum",
    [5035] = "The Vortex Pinnacle",
    [5042] = "Deepholm",
    [5088] = "The Stonecore",
    [5094] = "Blackrock Caverns",
    [5095] = "Grim Batol",
    [5144] = "Throne of the Four Winds",
    [5145] = "The Bastion of Twilight",
    [5287] = "The Deadmines",
    [5334] = "Shadowfang Keep",
    [5389] = "Tol Barad Peninsula",
    [5396] = "Tol Barad",
    [5600] = "Baradin Hold",
    [5723] = "Firelands",
    [5733] = "Molten Front",
    [5788] = "Well of Eternity",
    [5789] = "Dragon Soul",
    [5844] = "Scholomance",
    [5861] = "The Jade Forest",
    [5892] = "Scarlet Halls",
}

_G.professionMaster:CreateModel("zone-names-cata", zoneNames);
