--[[

@author Kurki
@copyright (c)2026 Profession Master. All Rights Reserved.

--]]

-- Zone name lookup for mop (auto-generated by tools/build-recipe-sources.ps1)
-- Keyed by zoneId (areaID), used to resolve zone names from recipe-sources data
local zoneNames = {
    [5736] = "The Wandering Isle",
    [5785] = "End Time",
    [5805] = "Darkmoon Island",
    [5840] = "Vale of Eternal Blossoms",
    [5841] = "Mogu'shan Vaults",
    [5842] = "Mogu'shan Palace",
    [5918] = "Scarlet Monastery",
    [5956] = "Temple of the Jade Serpent",
    [5963] = "Throne of Thunder",
    [6006] = "Heart of Fear",
    [6052] = "Stormstout Brewery",
    [6066] = "Terrace of Endless Spring",
    [6067] = "Siege of Niuzao Temple",
    [6109] = "Shado-Pan Monastery",
    [6125] = "Kun-Lai Summit",
    [6134] = "Krasarang Wilds",
    [6138] = "Dread Wastes",
    [6182] = "Townlong Steppes",
    [6208] = "Gate of the Setting Sun",
    [6214] = "Valley of the Four Winds",
    [6297] = "The Veiled Stair",
    [6500] = "Siege of Orgrimmar",
    [6507] = "Isle of Thunder",
    [6622] = "Timeless Isle",
    [6661] = "Isle of Giants",
    [6716] = "Deepwind Gorge",
}

_G.professionMaster:CreateModel("zone-names-mop", zoneNames);
