--[[

@author Kurki
@copyright (c)2026 Profession Master. All Rights Reserved.

--]]

-- Zone name lookup for wrath (auto-generated by tools/build-recipe-sources.ps1)
-- Keyed by zoneId (areaID), used to resolve zone names from recipe-sources data
local zoneNames = {
    [65] = "Dragonblight",
    [66] = "Zul'Drak",
    [67] = "Storm Peaks",
    [206] = "Utgarde Keep",
    [210] = "Icecrown",
    [394] = "Grizzly Hills",
    [495] = "Howling Fjord",
    [1196] = "Utgarde Pinnacle",
    [2159] = "Onyxia's Lair",
    [2817] = "Crystalsong Forest",
    [3537] = "Borean Tundra",
    [3711] = "Sholazar Basin",
    [4100] = "The Culling of Stratholme",
    [4196] = "Drak'Tharon Keep",
    [4197] = "Wintergrasp",
    [4228] = "The Oculus",
    [4264] = "Halls of Stone",
    [4265] = "The Nexus",
    [4272] = "Halls of Lightning",
    [4273] = "Ulduar",
    [4277] = "Azjol-Nerub",
    [4298] = "Plaguelands: The Scarlet Enclave",
    [4395] = "Dalaran",
    [4415] = "The Violet Hold",
    [4416] = "Gundrak",
    [4493] = "The Obsidian Sanctum",
    [4494] = "Ahn'kahet: The Old Kingdom",
    [4603] = "Vault of Archavon",
    [4722] = "Lost City of the Tol'vir",
    [4723] = "Halls of Origination",
    [4809] = "The Forge of Souls",
    [4812] = "Icecrown Citadel",
    [4813] = "Pit of Saron",
    [4820] = "Halls of Reflection",
}

_G.professionMaster:CreateModel("zone-names-wrath", zoneNames);
